### ISSUE TITLE
Python version recommandation and spyder interpreter

### ISSUE THREAD

**Issue by simonpatry14** [datovar4/Ai_Literature_Review_Suite#1]
Hello, 

Thanks for this great release! Sorry for this request
But I tried several time your installation protocol on a Windows 10 pro X64 system and encountered several issues. 
Which Python version do you recommend for your AiLiteratureReviewSuite? When using the default conda installation of the "requirements_win.txt" the process stops after line 107.  Before this, if I install your suite with Python 3.9 it works. But the spyder interpreter doesn't work in the AilitReview envs after installation. 

Many thanks for your help !

**Comment by datovar4** [comment]
Hi, thanks for your interest. I updated the environment files a few months ago, but forgot to update the ReadMe. It's updated now, please give it a try with: conda env create -f lit_environment_win.yml

**Comment by simonpatry14** [comment]
Thanks for your reply, I cleaned my envs, start a next LitReview envs and charged both lit_environement_win.yml and win_requirements.txt and finished the installation without any issue thanks you very much. spyder work and GUI start as intended.
